### ISSUE TITLE
ふりかえり

### ISSUE THREAD

**Issue by nouka** [oz-sysb/MerryMurakami#25]
## TRYリスト
- [ ] テストを動かす
- [ ] デモの準備をする
- [x] 設計をシンプルにする
  - ギザ10にこだわらない
  - 電源落としてお金が消えてもいい
  - 表示さんとかいらない
  - 結合度が高いのを考え直す
  - お金クラスとかやめてみる
- [ ] 命名を英語でそろえる
- [ ] PHP5.6的な書き方してみる
  - namespace, useを使い倒してみる

**Comment by a-kurasawa** [comment]
写真あげときます。
![image](https://cloud.githubusercontent.com/assets/7553840/8699188/a3ebe8be-2b3e-11e5-949e-a6b7c16b192b.jpg)
